# Generated by Django 2.1.7 on 2019-03-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190316_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addGu', models.CharField(max_length=50)),
                ('addDong', models.CharField(max_length=50)),
                ('addDetail', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('lng', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.City')),
            ],
        ),
    ]
