# Generated by Django 2.1.7 on 2019-03-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190316_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addDong', models.CharField(max_length=10, null=True)),
                ('houseNum', models.CharField(max_length=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'occupied'), (1, 'available')])),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apts', to='user.Apt')),
            ],
        ),
    ]
